#!/bin/sh

git update-index -q --refresh

u="$(git ls-files --exclude-standard --others 2>&1)"
if [[ ! -z $u ]]; then
	echo 1
fi

git diff-index --quiet --cached HEAD -- 2>&1 > /dev/null
u=$?
if [[ ! -z $u ]]; then
	echo 1
fi

git diff-files --quiet 2>&1 > /dev/null
u=$?
if [[ ! -z $u ]]; then
	echo 1
fi

echo 0
