#ifdef VKFNGLOBALPROC
	VKFNGLOBALPROC(vkEnumerateInstanceVersion)
	VKFNGLOBALPROC(vkEnumerateInstanceExtensionProperties)
	VKFNGLOBALPROC(vkEnumerateInstanceLayerProperties)
	VKFNGLOBALPROC(vkCreateInstance)
#endif
